### ISSUE TITLE
Projektdaten mappen und einspielen

### ISSUE THREAD

**Issue by dofeldsc** [FISvirtUOS/uos-vivo-ontology#1]
Eine Sammlung der verwendeten und noch fehlenden Properties für das Einspielen der Projektdaten

Die Klasse ist kdsf:Drittmittelprojekt

bis jetzt werden abgebildet:
- Beschreibung
- Titel
- Datum/Uhrzeit-Intervall => in Laufzeit umbenennen
- Bewilligungssumme (Anzeige überarbeiten, mit Euro und Trennzeichen für Tausender)
- Fach
- Mittelgeber (mapping auf kdsf Instanzen)
- Koordinationsrolle (Einrichtung) nur ja oder nein (Abändern das nicht true, false da steht)
- Organisationseinheit => Fachbereich/academic department  und Institute (Range ändern)
- TeilnehmerIn (name, Vorname und Rolle)
- übergeordnetes Projekt

fehlt noch (also einabuen)
- "Verbund/Partnerorganisation (Drittmittelprojekt <=> Organisationseinheit)
- "Ergebniszusammenfassung"
- "Externe Projektseite" Link
- "Schlagwörter" (mehrere Textfelder)

**Comment by dofeldsc** [comment]
Alles erledigt außer "Laufzeit".
Da gibt es ein Problem und ich habe es jetzt erstmal gelöst aber das müsste man sich nochmal anschauen.

Das Problem ist, wenn man eine eigene Property dafür anlegen würde und date/Time Interval als range nimmt dann erscheint zwar die Prop aber man kann kein Interval erzeugen. (Das liegt daran das die alte Prop ein eigenes Template dafür hat). Benutzt man jetzt bei den neuen Prop dieses Template dann landen die Einträge einfach bei der alten Prop.

Also kann/sollte man eine Faux-Property über die Oberfläche anlegen und genau darauf zuschneiden (Domain, Range). Das Problem ist wie kriegt man mehrsprachige Labels rein und wie sichert man das, also wo befinden sich die faux-Properties?

**Comment by ghost** [comment]
Auch wenn noch einiges für uns zu tun bleibt, sieht die Projektseite schon gut aus! Gute Arbeit :)

**Comment by dofeldsc** [comment]
Ich habe in der gelieferten Datei noch folgendes geändert:
- Leerzeichen in den Titeln der Spalten entfernt
- Das Ü des Spaltennamen "ÜbergeordnetesProjekt" in Ue geändert
- Das ö aus "Schlagwörter" in oe geändert

Noch eine Frage, die Verbund-/Partnerorganisationenen sollen schon als Objekte angelegt werden und nicht nur als String hinterlegt werden oder? 
Dann wird der Eintrag "Deutsche Sporthochschule Köln (DSHS Köln), Hochschule für angewandte Wissenschaften Coburg, Hochschule Magdeburg-Stendal, Leuphana Universität Lüneburg, Medizinische Hochschule Hannover (MHH), Universitätsklinikum Hamburg Eppendorf (UKE)" beim letzten Projekt nicht funktionieren. Ich habe ja schon erwähnt das immer nur ein Objekt pro Spalte möglich ist.

**Comment by dofeldsc** [comment]
Also wie abgesprochen werden die Verbund-/Partnerorganisationen nochmal separat geliefert. 

Wenn ihr das einschränken könnt wie viele Partnerorganisationen es gibt, dann kann man das auch über eigene Spalten in der Liste machen aber die Anzahl kann leider nicht variabel sein.

**Comment by dofeldsc** [comment]
Kann das wohl sein das bei den Mitarbeitern "Net-IDs" vorkommen die es im System nocht nicht gibt? :-/
